#!/usr/bin/env python3
"""Validate GCS Raw & Normalized Parquet outputs."""
from __future__ import annotations

import argparse
import io
import json
import sys
import os
import re
from datetime import datetime, timedelta
from pathlib import Path
import pandas as pd
from google.cloud import storage

ROOT = Path(__file__).resolve().parents[2]


def resolve_default_period(period_arg: str | None) -> str:
    """Resolve period string: explicit CLI arg -> ENV var -> latest folder on disk -> previous month."""
    if period_arg and period_arg.strip():
        return period_arg.strip()

    env_period = os.getenv("PERIOD", "").strip()
    if env_period:
        return env_period

    for base in [ROOT / "data" / "parsed" / "monthly", ROOT / "data" / "disclosures" / "monthly"]:
        if base.exists():
            date_dirs = sorted([d.name for d in base.iterdir() if d.is_dir() and re.match(r"^\d{4}-\d{2}", d.name)], reverse=True)
            if date_dirs:
                return date_dirs[0][:7] if len(date_dirs[0]) >= 7 else date_dirs[0]

    now = datetime.now()
    first_of_this_month = now.replace(day=1)
    last_month = first_of_this_month - timedelta(days=1)
    return last_month.strftime("%Y-%m")


def validate_gcp(bucket_name: str, period: str, amc_filter: str | None = None) -> dict:
    client = storage.Client()
    bucket = client.bucket(bucket_name)

    raw_prefix = "fund_holdings/raw/monthly/"
    raw_blobs = [b for b in bucket.list_blobs(prefix=raw_prefix) if period in b.name and (not amc_filter or f"/{amc_filter}/" in b.name)]
    
    # 1. Discover the target schemes generated by this run
    target_amfi_codes = set()
    parsed_base = ROOT / "data" / "parsed"
    if parsed_base.exists():
        for pj in parsed_base.rglob("portfolio.json"):
            if amc_filter and f"/{amc_filter}/" not in str(pj).replace("\\", "/"):
                continue
            try:
                data = json.loads(pj.read_text(encoding="utf-8"))
                c = str(data.get("meta", {}).get("amfi_code") or "").strip()
                if c:
                    target_amfi_codes.add(c)
            except Exception:
                pass

    norm_prefix = f"fund_holdings/normalized/as_of="
    all_parquet_blobs = list(bucket.list_blobs(prefix=norm_prefix))
    
    if target_amfi_codes:
        parquet_blobs = [b for b in all_parquet_blobs if b.name.split("/")[-1].replace(".parquet", "") in target_amfi_codes and period in b.name]
    elif amc_filter:
        parquet_blobs = [b for b in all_parquet_blobs if period in b.name and (b.metadata and b.metadata.get("amc_id") == amc_filter)]
    else:
        parquet_blobs = [b for b in all_parquet_blobs if b.name.endswith(".parquet") and period in b.name]

    print(f"\n--- [GCP Audit] Raw Files: {len(raw_blobs)}, Target Parquet Schemes to Validate: {len(parquet_blobs)} ---")
    
    total_rows = 0
    errors = []
    schemes_verified = []

    for b in parquet_blobs:
        try:
            live_blob = bucket.blob(b.name)
            content = live_blob.download_as_bytes()
            df = pd.read_parquet(io.BytesIO(content))

            row_count = len(df)
            total_rows += row_count
            amfi_code = b.name.split("/")[-1].replace(".parquet", "")

            for col in ["amfi_code", "instrument", "market_value", "pct_nav", "holding_type"]:
                if col not in df.columns:
                    errors.append(f"{b.name}: missing column {col}")

            if row_count == 0:
                errors.append(f"{b.name}: 0 rows")

            scheme_name = df["amfi_name"].iloc[0] if "amfi_name" in df.columns and len(df) > 0 else "unknown"
            print(f"  ✓ [AMFI: {amfi_code}] {scheme_name}: {row_count} rows")
            schemes_verified.append({"amfi_code": amfi_code, "rows": row_count})
        except Exception as err:
            errors.append(f"{b.name}: {err}")
            print(f"  ✗ [Error] {b.name}: {err}")

    passed = len(errors) == 0 and len(schemes_verified) > 0
    print(f"\n=== GCP Validation Status: {'PASS' if passed else 'FAIL'} (Verified Schemes: {len(schemes_verified)}, Total Rows: {total_rows}) ===")
    return {"passed": passed, "total_rows": total_rows, "errors": errors}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bucket", required=True)
    ap.add_argument("--period", required=False, default=None, help="Period YYYY-MM (defaults to auto-detected previous month)")
    ap.add_argument("--amc")
    args = ap.parse_args()
    period = resolve_default_period(args.period)
    res = validate_gcp(args.bucket, period, args.amc)
    return 0 if res["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())

